# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dec593bced65fb3ddc93402d9b38f4ed9ea7dbd02afb5dd377af45aec6eec2cb967a55d17649e88eb63a6cc6ea596493f01140bf32e0b6ceb03986d0b6513539

test:
  secret_key_base: d6678961fc2f59592d520e4f66777d6d712795f1fde1e9f614f738a000af01903e1113aae2aac312e1cc3ec2dfcc17fa65d51dcb2acb426694f905f4f013907e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
